// Build src/core/fonts.js: the poster fonts' metadata and metrics.
//
// Inputs (src/assets/fonts/):
//   <id>.woff2     the Google Fonts "latin" subset of each font (served as an
//                  asset and embedded into posters at export time)
//   metrics.json   per font: cap height, ascender, descender and the advance
//                  width (1/1000 em) of every supported character, measured
//                  in Chromium with canvas measureText on those same files
// Run: node scripts/build-fonts.mjs
import { readFileSync, writeFileSync } from 'node:fs';

const dir = new URL('../src/assets/fonts/', import.meta.url);
const metrics = JSON.parse(readFileSync(new URL('metrics.json', dir), 'utf8'));

const FONTS = [
  { id: 'momo', label: 'Momo Trust Display', family: 'Momo Trust Display', weight: 400 },
  { id: 'archivo-black', label: 'Archivo Black', family: 'Archivo Black', weight: 400 },
  { id: 'anton', label: 'Anton', family: 'Anton', weight: 400 },
  { id: 'bricolage', label: 'Bricolage Grotesque', family: 'Bricolage Grotesque', weight: 800 },
  { id: 'space-grotesk', label: 'Space Grotesk', family: 'Space Grotesk', weight: 700 },
  { id: 'fraunces', label: 'Fraunces', family: 'Fraunces', weight: 900 },
  { id: 'dm-serif', label: 'DM Serif Display', family: 'DM Serif Display', weight: 400 },
];

const charset = metrics[FONTS[0].id].chars;
const entries = FONTS.map((f) => {
  const m = metrics[f.id];
  if (m.chars !== charset) throw new Error(`charset differs for ${f.id}`);
  return `  { id: '${f.id}', label: '${f.label}', family: '${f.family}', weight: ${f.weight}, cap: ${m.cap}, ascender: ${m.ascender}, desc: ${m.desc},
    adv: [${m.adv.join(',')}] }`;
});

writeFileSync(new URL('../src/core/fonts.js', import.meta.url), `// Generated by scripts/build-fonts.mjs. Do not edit by hand.
//
// Poster fonts (Google Fonts, SIL Open Font License 1.1, see
// src/assets/fonts/licenses/). The font files themselves are assets
// (src/assets/fonts/<id>.woff2), loaded on demand and embedded into posters.
// \`adv\` holds each character's advance width in 1/1000 em, in CHARSET order.

export const CHARSET = ${JSON.stringify(charset)};

export const FONTS = [
${entries.join(',\n')},
];

export const DEFAULT_FONT = 'momo';
`);
console.log(`wrote ${FONTS.length} fonts, ${charset.length} characters each`);
